/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_MY_LIB_H
#define _MOCK_MY_LIB_H

#include "unity.h"
#include "my_lib.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_my_lib_Init(void);
void mock_my_lib_Destroy(void);
void mock_my_lib_Verify(void);




#define calc_sum_IgnoreAndReturn(cmock_retval) calc_sum_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void calc_sum_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define calc_sum_StopIgnore() calc_sum_CMockStopIgnore()
void calc_sum_CMockStopIgnore(void);
#define calc_sum_ExpectAnyArgsAndReturn(cmock_retval) calc_sum_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void calc_sum_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define calc_sum_ExpectAndReturn(a, b, cmock_retval) calc_sum_CMockExpectAndReturn(__LINE__, a, b, cmock_retval)
void calc_sum_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int a, int b, int cmock_to_return);
typedef int (* CMOCK_calc_sum_CALLBACK)(int a, int b, int cmock_num_calls);
void calc_sum_AddCallback(CMOCK_calc_sum_CALLBACK Callback);
void calc_sum_Stub(CMOCK_calc_sum_CALLBACK Callback);
#define calc_sum_StubWithCallback calc_sum_Stub
#define calc_sum_IgnoreArg_a() calc_sum_CMockIgnoreArg_a(__LINE__)
void calc_sum_CMockIgnoreArg_a(UNITY_LINE_TYPE cmock_line);
#define calc_sum_IgnoreArg_b() calc_sum_CMockIgnoreArg_b(__LINE__)
void calc_sum_CMockIgnoreArg_b(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
