/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_my_lib.h"

static const char* CMockString_a = "a";
static const char* CMockString_b = "b";
static const char* CMockString_calc_sum = "calc_sum";

typedef struct _CMOCK_calc_sum_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  int Expected_a;
  int Expected_b;
  char IgnoreArg_a;
  char IgnoreArg_b;

} CMOCK_calc_sum_CALL_INSTANCE;

static struct mock_my_libInstance
{
  char calc_sum_IgnoreBool;
  int calc_sum_FinalReturn;
  char calc_sum_CallbackBool;
  CMOCK_calc_sum_CALLBACK calc_sum_CallbackFunctionPointer;
  int calc_sum_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE calc_sum_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_my_lib_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.calc_sum_CallInstance;
  if (Mock.calc_sum_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_calc_sum);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.calc_sum_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_my_lib_Init(void)
{
  mock_my_lib_Destroy();
}

void mock_my_lib_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int calc_sum(int a, int b)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_calc_sum_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_calc_sum);
  cmock_call_instance = (CMOCK_calc_sum_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.calc_sum_CallInstance);
  Mock.calc_sum_CallInstance = CMock_Guts_MemNext(Mock.calc_sum_CallInstance);
  if (Mock.calc_sum_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.calc_sum_FinalReturn;
    Mock.calc_sum_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.calc_sum_CallbackBool &&
      Mock.calc_sum_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.calc_sum_CallbackFunctionPointer(a, b, Mock.calc_sum_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_a)
  {
    UNITY_SET_DETAILS(CMockString_calc_sum,CMockString_a);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_a, a, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_b)
  {
    UNITY_SET_DETAILS(CMockString_calc_sum,CMockString_b);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_b, b, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.calc_sum_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.calc_sum_CallbackFunctionPointer(a, b, Mock.calc_sum_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_calc_sum(CMOCK_calc_sum_CALL_INSTANCE* cmock_call_instance, int a, int b);
void CMockExpectParameters_calc_sum(CMOCK_calc_sum_CALL_INSTANCE* cmock_call_instance, int a, int b)
{
  cmock_call_instance->Expected_a = a;
  cmock_call_instance->IgnoreArg_a = 0;
  cmock_call_instance->Expected_b = b;
  cmock_call_instance->IgnoreArg_b = 0;
}

void calc_sum_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_sum_CALL_INSTANCE));
  CMOCK_calc_sum_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_sum_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_sum_CallInstance = CMock_Guts_MemChain(Mock.calc_sum_CallInstance, cmock_guts_index);
  Mock.calc_sum_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.calc_sum_IgnoreBool = (char)1;
}

void calc_sum_CMockStopIgnore(void)
{
  if(Mock.calc_sum_IgnoreBool)
    Mock.calc_sum_CallInstance = CMock_Guts_MemNext(Mock.calc_sum_CallInstance);
  Mock.calc_sum_IgnoreBool = (char)0;
}

void calc_sum_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_sum_CALL_INSTANCE));
  CMOCK_calc_sum_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_sum_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_sum_CallInstance = CMock_Guts_MemChain(Mock.calc_sum_CallInstance, cmock_guts_index);
  Mock.calc_sum_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void calc_sum_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int a, int b, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_sum_CALL_INSTANCE));
  CMOCK_calc_sum_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_sum_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_sum_CallInstance = CMock_Guts_MemChain(Mock.calc_sum_CallInstance, cmock_guts_index);
  Mock.calc_sum_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_calc_sum(cmock_call_instance, a, b);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void calc_sum_AddCallback(CMOCK_calc_sum_CALLBACK Callback)
{
  Mock.calc_sum_IgnoreBool = (char)0;
  Mock.calc_sum_CallbackBool = (char)1;
  Mock.calc_sum_CallbackFunctionPointer = Callback;
}

void calc_sum_Stub(CMOCK_calc_sum_CALLBACK Callback)
{
  Mock.calc_sum_IgnoreBool = (char)0;
  Mock.calc_sum_CallbackBool = (char)0;
  Mock.calc_sum_CallbackFunctionPointer = Callback;
}

void calc_sum_CMockIgnoreArg_a(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_calc_sum_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_sum_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.calc_sum_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_a = 1;
}

void calc_sum_CMockIgnoreArg_b(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_calc_sum_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_sum_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.calc_sum_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_b = 1;
}

