/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_MATH_LIB_H
#define _MOCK_MATH_LIB_H

#include "unity.h"
#include "math_lib.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_math_lib_Init(void);
void mock_math_lib_Destroy(void);
void mock_math_lib_Verify(void);




#define sum_two_ints_IgnoreAndReturn(cmock_retval) sum_two_ints_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void sum_two_ints_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define sum_two_ints_StopIgnore() sum_two_ints_CMockStopIgnore()
void sum_two_ints_CMockStopIgnore(void);
#define sum_two_ints_ExpectAnyArgsAndReturn(cmock_retval) sum_two_ints_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void sum_two_ints_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define sum_two_ints_ExpectAndReturn(a, b, cmock_retval) sum_two_ints_CMockExpectAndReturn(__LINE__, a, b, cmock_retval)
void sum_two_ints_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int a, int b, int cmock_to_return);
typedef int (* CMOCK_sum_two_ints_CALLBACK)(int a, int b, int cmock_num_calls);
void sum_two_ints_AddCallback(CMOCK_sum_two_ints_CALLBACK Callback);
void sum_two_ints_Stub(CMOCK_sum_two_ints_CALLBACK Callback);
#define sum_two_ints_StubWithCallback sum_two_ints_Stub
#define sum_two_ints_IgnoreArg_a() sum_two_ints_CMockIgnoreArg_a(__LINE__)
void sum_two_ints_CMockIgnoreArg_a(UNITY_LINE_TYPE cmock_line);
#define sum_two_ints_IgnoreArg_b() sum_two_ints_CMockIgnoreArg_b(__LINE__)
void sum_two_ints_CMockIgnoreArg_b(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
